### ISSUE TITLE
Please update to API 5.0

### ISSUE THREAD

**Issue by crymates** [randombyte-developer/server-tours#2]
Currently server crashs if trying to use the plugin :/

**Comment by randombyte-developer** [comment]
This plugin isn't built against api v5. Please post the crashlog if the server crashes. 
I'll update the plugin soooooon.

**Comment by crymates** [comment]
That crash log is really big, I also can search for your plugin logs manually if you wish.
Thx for your quick answer btw!

[crash_log.txt](https://github.com/randombyte-developer/server-tours/files/543201/crash_log.txt)

**Comment by randombyte-developer** [comment]
Ok, that's a very straight forward crashlog. I'll update it soooonish. ☺

**Comment by randombyte-developer** [comment]
https://github.com/randombyte-developer/server-tours/releases
Updated
